version: 2.1

executors:
  default:
    docker:
      - image: circleci/golang:1.14.1
        name: golang
    working_directory: /go/src/github.com/medi-taketani/training

jobs:
  build:
    executor: default
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: cd go_test && go get -v -t -d ./...
      - run: cd go_test && go test -v ./...
workflows:
  version: 2
  default:
    jobs:
      - build:
        filters:
          branches:
            only:
              - dev
              - /dev\/*/