name: "Schedule Tag Tests"
on:
  schedule:
    - cron: '13 7 * * *'
jobs:
  add_tag:
    name: add_tag
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: git tag
        run: |
          DATE=`date +"%Y%m%d"`
          TAG_NAME="dev-$DATE_1"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
        env:
          TZ: 'Asia/Tokyo' 
